export class Person {
    id: number;
    uuid: string;
    title_option_id: number;
    first_name: string; // required
    middle_name: string;
    last_name: string; // required
    suffix_option_id: number;
    national_id: string;
    file_number: string;
    birthdate: string;
    genderid: number; // required - was previously string with field name gender
    facility_id: number; // required
    multi_facility_ids: string;
    phone_work: string;
    phone_mobile: string;
    fax: string;
    phone_home: string;
    email: string;
    email_secondary: string;
    primary_qualification_option_id: number; // required
    primary_responsibility_option_id: number;
    secondary_responsibility_option_id: number;
    comments: string;
    person_custom_1_option_id: number;
    person_custom_2_option_id: number;
    home_address_1: string;
    home_address_2: string;
    home_city: string;
    home_location_id: number;
    home_postal_code: number;
    home_is_residential: string;
    activeid: number;  // required - was previously string with field name active
    timestamp_created: string;
    timestamp_updated: string;
    created_by: number;
    modified_by: number;
    is_deleted: number;  // required
    highest_edu_level_option_id: number;
    attend_reason_option_id: number;
    attend_reason_other: string;
    highest_level_option_id: number;
    me_responsibility: string;
    mfl_code: number;  // required
    govemp_option_id: number;
    occupational_category_id: number;
    persal_number: number;
    bodies_id: number;
    race_option_id: number;
    disability_option_id: number;
    professional_reg_number: number;
    nationality_id: number;
    nurse_training_id: number;
    care_start_year: number;
    timespent_rank_pregnant: number;
    timespent_rank_adults: number;
    timespent_rank_children: number;
    timespent_rank_pregnant_pct: number;
    timespent_rank_adults_pct: number;
    timespent_rank_children_pct: number;
    supervised_id: number;
    supervision_frequency_id: number;
    supervisors_profession: string;
    training_recieved_data: string;
    facilitydepartment_id: number;
    custom_3: string;
    custom_4: string;
    custom_5: string;
    approved: number;
    custom_field1: string;
    custom_field2: string;
    custom_field3: string;
    marital_status: string;
    spouse_name: string;
    workplace_id: number;

    constructor(obj) {
        this.id = obj.id || null;
        this.uuid = obj.uuid || null;
        this.title_option_id = obj.title_option_id || null;
        this.first_name = obj.first_name || null;
        this.middle_name = obj.middle_name || null;
        this.last_name = obj.last_name || null;
        this.suffix_option_id = obj.suffix_option_id || null;
        this.national_id = obj.national_id || null;
        this.file_number = obj.file_number || null;
        this.birthdate = obj.birthdate || null;
        this.genderid = obj.genderid || null;
        this.facility_id = obj.facility_id || null;
        this.multi_facility_ids = obj.multi_facility_ids || null;
        this.phone_work = obj.phone_work || null;
        this.phone_mobile = obj.phone_mobile || null;
        this.fax = obj.fax || null;
        this.phone_home = obj.phone_home || null;
        this.email = obj.email || null;
        this.email_secondary = obj.email_secondary || null;
        this.primary_qualification_option_id = obj.primary_qualification_option_id || null;
        this.primary_responsibility_option_id = obj.primary_responsibility_option_id || null;
        this.secondary_responsibility_option_id = obj.secondary_responsibility_option_id || null;
        this.comments = obj.comments || null;
        this.person_custom_1_option_id = obj.person_custom_1_option_id || null;
        this.person_custom_2_option_id = obj.person_custom_2_option_id || null;
        this.home_address_1 = obj.home_address_1 || null;
        this.home_address_2 = obj.home_address_2 || null;
        this.home_city = obj.home_city || null;
        this.home_location_id = obj.home_location_id || null;
        this.home_postal_code = obj.home_postal_code || null;
        this.home_is_residential = obj.home_is_residential || null;
        this.activeid = obj.activeid || null;
        this.timestamp_created = obj.timestamp_created || null;
        this.timestamp_updated = obj.timestamp_updated || null;
        this.created_by = obj.created_by || null;
        this.modified_by = obj.modified_by || null;
        this.is_deleted = obj.is_deleted || 0;
        this.highest_edu_level_option_id = obj.highest_edu_level_option_id || null;
        this.attend_reason_option_id = obj.attend_reason_option_id || null;
        this.attend_reason_other = obj.attend_reason_other || null;
        this.highest_level_option_id = obj.highest_level_option_id || null;
        this.me_responsibility = obj.me_responsibility || null;
        this.mfl_code = obj.mfl_code || null;
        this.govemp_option_id = obj.govemp_option_id || null;
        this.occupational_category_id = obj.occupational_category_id || null;
        this.persal_number = obj.persal_number || null;
        this.bodies_id = obj.bodies_id || null;
        this.race_option_id = obj.race_option_id || null;
        this.disability_option_id = obj.disability_option_id || null;
        this.professional_reg_number = obj.professional_reg_number || null;
        this.nationality_id = obj.nationality_id || null;
        this.nurse_training_id = obj.nurse_training_id || null;
        this.care_start_year = obj.care_start_year || null;
        this.timespent_rank_pregnant = obj.timespent_rank_pregnant || null;
        this.timespent_rank_adults = obj.timespent_rank_adults || null;
        this.timespent_rank_children = obj.timespent_rank_children || null;
        this.timespent_rank_pregnant_pct = obj.timespent_rank_pregnant_pct || null;
        this.timespent_rank_adults_pct = obj.timespent_rank_adults_pct || null;
        this.timespent_rank_children_pct = obj.timespent_rank_children_pct || null;
        this.supervised_id = obj.supervised_id || null;
        this.supervision_frequency_id = obj.supervision_frequency_id || null;
        this.supervisors_profession = obj.supervisors_profession || null;
        this.training_recieved_data = obj.training_recieved_data || null;
        this.facilitydepartment_id = obj.facilitydepartment_id || null;
        this.custom_3 = obj.custom_3 || null;
        this.custom_4 = obj.custom_4 || null;
        this.custom_5 = obj.custom_5 || null;
        this.approved = obj.approved || null;
        this.custom_field1 = obj.custom_field1 || null;
        this.custom_field2 = obj.custom_field2 || null;
        this.custom_field3 = obj.custom_field3 || null;
        this.marital_status = obj.marital_status || null;
        this.spouse_name = obj.spouse_name || null;
        this.workplace_id = obj.workplace_id || null;
    }
}
